language: c

arch: arm64

compiler: gcc

before_install:
    - wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz -O /tmp/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz
    - unxz /tmp/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz
    - tar -xf /tmp/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar
    - export PATH=$PATH:$PWD/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf/bin/

script: make
